---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mime-wasm-ingress-custom-headers
data:
  Content-Type: application/wasm
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    nginx.ingress.kubernetes.io/custom-headers: {{ .Values.global.namespace }}/mime-wasm-ingress-custom-headers
    nginx.ingress.kubernetes.io/rewrite-target: /$1
  labels:
    component: app
    application: nos1000jours-landing
  name: mime-wasm
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.host }}
      http:
        paths:
          - backend:
              service:
                name: app
                port:
                  name: http
            path: /.*\.wasm\.gz$
            pathType: ImplementationSpecific
  tls:
    - hosts:
        - {{ .Values.global.host }}
      secretName: wildcard-crt