global:
  imageProject: 1000jours

app:
  ~chart: app
  imagePackage: app
  containerPort: 8080
  securityContext:
    fsGroup: 101
    runAsGroup: 101
    runAsUser: 101
  ingress:
    customHeaders:
      "Content-Security-Policy": "default-src 'self' data:; connect-src 'self' https://*.gouv.fr https://metrics.articulate.com; font-src 'self' data:; img-src 'self'; script-src 'self' https://*.gouv.fr 'unsafe-inline' 'unsafe-eval'; frame-src 'self' https://*.gouv.fr; style-src 'self' 'unsafe-inline'"
      "X-Frame-Options": "sameorigin"
      "X-XSS-Protection": "1; mode=block"
      "X-Content-Type-Options": "none"
